import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/Navbar'
import { Toaster } from "@/components/ui/toaster"
import QueryClientProvider from './QueryClientProvider'
import Provider from '@/components/Provider'
import { getServerSession } from 'next-auth'
import { options } from './api/auth/[...nextauth]/options'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const Session = getServerSession(options)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <QueryClientProvider>
          <Toaster/>
          <Navbar/>
            {children}
          </QueryClientProvider>
        </Provider>
        </body>
    </html>
  )
}
